name: Build Android

on:
  push:
    branches:
      - master
      
jobs:
  install:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install